fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    build_number = Time.new.strftime("%y%m%d%H%M")
    increment_build_number(
        build_number: build_number
    )
  end

  lane :beta do |values|
    gym(scheme: 'TimerH2O_BetaTest',
        configuration: 'Test',
        export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['alessio.roberto@gmail.com', 'alessia.gallian@gmail.com'] # You can list more emails here
    #emails = values[:test_email] ? values[:test_email] : ['alessio.roberto@gmail.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'f92187a6ad939c214258ffa2c9f03c6cc0a3d74d',
             build_secret: 'cf62acf20c611275d4126ffa3579a0861887c27a7a90007def0a96e8c0519d01',
                   emails: emails,
                   groups: groups,
                    notes: "changelog:\n"changelog, # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`
  end
end

def changelog()
   strip_emoji(changelog_from_git_commits(merge_commit_filtering: 'exclude_merges',
                                          pretty: "- (%ae) %s"))
end

def strip_emoji(text)
   text = text.force_encoding('utf-8').encode
   clean = ""

   # symbols & pics
   regex = /[\u{1f300}-\u{1f5ff}]/
   clean = text.gsub regex, ""

   # enclosed chars
   regex = /[\u{2500}-\u{2BEF}]/ # I changed this to exclude chinese char
   clean = clean.gsub regex, ""

   # emoticons
   regex = /[\u{1f600}-\u{1f64f}]/
   clean = clean.gsub regex, ""

   #dingbats
   regex = /[\u{2702}-\u{27b0}]/
   clean = clean.gsub regex, ""
 end
