fastlane_version "2.9.0"

default_platform :ios

platform :ios do
  before_all do
    build_number = Time.new.strftime("%y%m%d%H%M")
    increment_build_number(
        build_number: build_number
    )
  end

  desc "Submit to internal testers using Crashlytics"
  lane :alpha do |values|
    gym(scheme: 'TimerH2O_BetaTest',
        configuration: 'Test',
        export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : nil # You can list more emails here
    groups = values[:test_email] ? nil : ['Internal'] # You can define groups on the web and reference them here

    crashlytics(api_token: 'f92187a6ad939c214258ffa2c9f03c6cc0a3d74d',
             build_secret: 'cf62acf20c611275d4126ffa3579a0861887c27a7a90007def0a96e8c0519d01',
                   emails: emails,
                   groups: groups,
                    notes: changelog, # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?
  end

  desc "Submit to internal and external testers using Crashlytics"
  lane :beta do |values|
    gym(scheme: 'TimerH2O_BetaTest',
        configuration: 'Test',
        export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : nil # You can list more emails here
    groups = values[:test_email] ? nil : ['External', 'Internal'] # You can define groups on the web and reference them here

    crashlytics(api_token: 'f92187a6ad939c214258ffa2c9f03c6cc0a3d74d',
             build_secret: 'cf62acf20c611275d4126ffa3579a0861887c27a7a90007def0a96e8c0519d01',
                   emails: emails,
                   groups: groups,
                    notes: changelog, # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :finalTest do
    gym(scheme: "TimerH2O_BetaTest",
        configuration: 'Test')

    pilot(
      changelog: changelog, # Check out the changelog_from_git_commits action
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end

  desc "Create screenshots"
  lane :screenshots do
    snapshot(
        scheme: "TimerH2O_BetaTest",
        languages:["it_IT", "en_US"],
        stop_after_first_error: true,
        verbose: false,
        devices:["iPhone 5s", "iPhone 7", "iPhone 7 Plus"],
        clean: true
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    gym(scheme: "TimerH2O")

    deliver(
      app_version: "1.0.2",
      force: true
    )
    # frameit
  end
end

def changelog()
   strip_emoji(changelog_from_git_commits(merge_commit_filtering: 'exclude_merges',
                                          pretty: "- (%ae) %s"))
end

def strip_emoji(text)
   text = text.force_encoding('utf-8').encode
   clean = ""

   # symbols & pics
   regex = /[\u{1f300}-\u{1f5ff}]/
   clean = text.gsub regex, ""

   # enclosed chars
   regex = /[\u{2500}-\u{2BEF}]/ # I changed this to exclude chinese char
   clean = clean.gsub regex, ""

   # emoticons
   regex = /[\u{1f600}-\u{1f64f}]/
   clean = clean.gsub regex, ""

   #dingbats
   regex = /[\u{2702}-\u{27b0}]/
   clean = clean.gsub regex, ""
 end
