disabled_rules:
  - trailing_whitespace

opt_in_rules: # some rules are only opt-in
  - force_unwrapping
  - overridden_super_call
  - redundant_nil_coalescing

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage
  - R.generated.swift

line_length:
    warning: 175
    error: 220

variable_name:
    min_length: 2

type_name:
    max_length: 50
