project 'TimerH2O.xcodeproj'

platform :ios, '9.0'

target 'TimerH2O' do
  use_frameworks!
  # Pods for TimerH2O
  pod 'R.swift'
  pod 'Fabric'
  pod 'Crashlytics', '~>  3.9'
  pod 'RealmSwift'
  pod 'SVProgressHUD'
  pod 'Instructions'
  pod 'Firebase/Core'
  #pod 'Charts'

  target 'TimerH2OTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
